---
title: "Data preperation all studies"
author: "Julius Fenn, Laura Londoño"
format:
  html:
    toc: true
    toc-depth: 3
    html-math-method: katex
    number-sections: true
---


# Notes


# global variables

Define your global variables (e.g., to reduce run time):

```{r}
#| label: global variables

# aaa
```

# functions

```{r}
########################################
# aaa
########################################
### args:
# aaa = bbb

```


# load packages

```{r}
#| label: load packages
#| warning: false

### load packages (also packages loaded, which are not needed for data preperation)
require(pacman)
p_load('tidyverse',
       'stargazer',  'DT', 'psych',
       'writexl', 'readxl', 'haven')
```

# load and prepare raw data files

corrupt csv file: 

```{r}
setwd("data")

con <- file("data_Carerobots_2026-01-27_10-05.csv", open = "r", encoding = "UTF-16")
head(readLines(con, n = 4), warn = FALSE)
close(con)
```



```{r}
# Define the classes based on your colClasses logic
type_map <- c(
  CASE="numeric", SERIAL="character", REF="character", QUESTNNR="character",
  MODE="factor", STARTED="POSIXct", A011_01="numeric", A011_02="numeric",
  A012="numeric", A012_01="logical", A012_02="logical", A012_03="logical",
  A012_04="logical", A012_05="logical", A012_06="logical",
  A012_06a="character", A014_01="character", A014_02="character",
  A014_03="character", A015_01="numeric", A015_02="numeric",
  A015_03="numeric", A015_04="numeric", A016_01="numeric", A016_02="numeric",
  A016_03="numeric", A016_04="numeric", A017_01="numeric", A017_02="numeric",
  A017_03="numeric", A017_04="numeric", A018_01="numeric", A018_02="numeric",
  A018_03="numeric", A019_01="numeric", A019_02="numeric", A019_03="numeric",
  A019_04="numeric", A019_05="numeric", A019_06="numeric", A019_07="numeric",
  A110_01="numeric", A110_02="numeric", A111="numeric", A111_01="logical",
  A111_02="logical", A111_03="logical", A111_04="logical", A111_05="logical",
  A111_06="logical", A111_06a="character", A112_01="character",
  A112_02="character", A112_03="character", A113_01="numeric",
  A113_02="numeric", A113_03="numeric", A113_04="numeric", A114_01="numeric",
  A114_02="numeric", A114_03="numeric", A114_04="numeric", A115_01="numeric",
  A115_02="numeric", A115_03="numeric", A115_04="numeric", A116_01="numeric",
  A116_02="numeric", A116_03="numeric", A117_01="numeric", A117_02="numeric",
  A117_03="numeric", A117_04="numeric", A117_05="numeric", A117_06="numeric",
  A117_07="numeric", A209_01="numeric", A209_02="numeric", A211="numeric",
  A211_01="logical", A211_02="logical", A211_03="logical", A211_04="logical",
  A211_05="logical", A211_06="logical", A211_06a="character",
  A212_01="character", A212_02="character", A212_03="character",
  A213_01="numeric", A213_02="numeric", A213_03="numeric", A213_04="numeric",
  A214_01="numeric", A214_02="numeric", A214_03="numeric", A214_04="numeric",
  A215_01="numeric", A215_02="numeric", A215_03="numeric", A215_04="numeric",
  A216_01="numeric", A216_02="numeric", A216_03="numeric", A217_01="numeric",
  A217_02="numeric", A217_03="numeric", A217_04="numeric", A217_05="numeric",
  A217_06="numeric", A217_07="numeric", A310_01="numeric", A310_02="numeric",
  A311="numeric", A311_01="logical", A311_02="logical", A311_03="logical",
  A311_04="logical", A311_05="logical", A311_06="logical",
  A311_06a="character", A312_01="character", A312_02="character",
  A312_03="character", A313_01="numeric", A313_02="numeric",
  A313_03="numeric", A313_04="numeric", A314_01="numeric", A314_02="numeric",
  A314_03="numeric", A314_04="numeric", A315_01="numeric", A315_02="numeric",
  A315_03="numeric", A315_04="numeric", A316_01="numeric", A316_02="numeric",
  A316_03="numeric", A317_01="numeric", A317_02="numeric", A317_03="numeric",
  A317_04="numeric", A317_05="numeric", A317_06="numeric", A317_07="numeric",
  A401="numeric", A701_01="numeric", A702="numeric", A702_05="character",
  A703="numeric", A705_01="character", D101_01="numeric", D101_02="numeric",
  D102="numeric", D102_01="logical", D102_02="logical", D102_03="logical",
  D102_04="logical", D102_05="logical", D102_06="logical",
  D102_06a="character", D103_01="character", D103_02="character",
  D103_03="character", D104_01="numeric", D104_02="numeric",
  D104_03="numeric", D104_04="numeric", D105_01="numeric", D105_02="numeric",
  D105_03="numeric", D105_04="numeric", D106_01="numeric", D106_02="numeric",
  D106_03="numeric", D106_04="numeric", D107_01="numeric", D107_02="numeric",
  D107_03="numeric", D108_01="numeric", D108_02="numeric", D108_03="numeric",
  D108_04="numeric", D108_05="numeric", D108_06="numeric", D108_07="numeric",
  D201_01="numeric", D201_02="numeric", D202="numeric", D202_01="logical",
  D202_02="logical", D202_03="logical", D202_04="logical", D202_05="logical",
  D202_06="logical", D202_06a="character", D203_01="character",
  D203_02="character", D203_03="character", D204_01="numeric",
  D204_02="numeric", D204_03="numeric", D204_04="numeric", D205_01="numeric",
  D205_02="numeric", D205_03="numeric", D205_04="numeric", D206_01="numeric",
  D206_02="numeric", D206_03="numeric", D206_04="numeric", D207_01="numeric",
  D207_02="numeric", D207_03="numeric", D208_01="numeric", D208_02="numeric",
  D208_03="numeric", D208_04="numeric", D208_05="numeric", D208_06="numeric",
  D301_01="numeric", D301_02="numeric", D302="numeric", D302_01="logical",
  D302_02="logical", D302_03="logical", D302_04="logical", D302_05="logical",
  D302_06="logical", D302_06a="character", D303_01="character",
  D303_02="character", D303_03="character", D304_01="numeric",
  D304_02="numeric", D304_03="numeric", D304_04="numeric", D305_01="numeric",
  D305_02="numeric", D305_03="numeric", D305_04="numeric", D306_01="numeric",
  D306_02="numeric", D306_03="numeric", D306_04="numeric", D307_01="numeric",
  D307_02="numeric", D307_03="numeric", D308_01="numeric", D308_02="numeric",
  D308_03="numeric", D308_04="numeric", D308_05="numeric", D308_06="numeric",
  D401_01="numeric", D401_02="numeric", D402="numeric", D402_01="logical",
  D402_02="logical", D402_03="logical", D402_04="logical", D402_05="logical",
  D402_06="logical", D402_06a="character", D403_01="character",
  D403_02="character", D403_03="character", D404_01="numeric",
  D404_02="numeric", D404_03="numeric", D404_04="numeric", D405_01="numeric",
  D405_02="numeric", D405_03="numeric", D405_04="numeric", D406_01="numeric",
  D406_02="numeric", D406_03="numeric", D406_04="numeric", D407_01="numeric",
  D407_02="numeric", D407_03="numeric", D408_01="numeric", D408_02="numeric",
  D408_03="numeric", D408_04="numeric", D408_05="numeric", D408_06="numeric",
  D501="numeric", D801_01="character", D802="numeric", D803="numeric",
  D804_01="character", RA01_CP="numeric", RA01="numeric", TIME001="integer",
  TIME002="integer", TIME003="integer", TIME004="integer", TIME005="integer",
  TIME006="integer", TIME007="integer", TIME008="integer", TIME009="integer",
  TIME010="integer", TIME011="integer", TIME012="integer", TIME013="integer",
  TIME014="integer", TIME015="integer", TIME016="integer", TIME017="integer",
  TIME018="integer", TIME019="integer", TIME020="integer", TIME021="integer",
  TIME022="integer", TIME023="integer", TIME024="integer", TIME025="integer",
  TIME_SUM="integer", MAILSENT="POSIXct", LASTDATA="POSIXct",
  STATUS="character", FINISHED="logical", Q_VIEWER="logical",
  LASTPAGE="numeric", MAXPAGE="numeric", MISSING="numeric", MISSREL="numeric",
  TIME_RSI="numeric"
)
```





```{r}
setwd("data")

# 1. Define the column names (extracted from your script)
col_names_vec <- c(
  "CASE","SERIAL","REF","QUESTNNR","MODE","STARTED","A011_01","A011_02","A012",
  "A012_01","A012_02","A012_03","A012_04","A012_05","A012_06","A012_06a",
  "A014_01","A014_02","A014_03","A015_01","A015_02","A015_03","A015_04","A016_01",
  "A016_02","A016_03","A016_04","A017_01","A017_02","A017_03","A017_04","A018_01",
  "A018_02","A018_03","A019_01","A019_02","A019_03","A019_04","A019_05","A019_06",
  "A019_07","A110_01","A110_02","A111","A111_01","A111_02","A111_03","A111_04",
  "A111_05","A111_06","A111_06a","A112_01","A112_02","A112_03","A113_01",
  "A113_02","A113_03","A113_04","A114_01","A114_02","A114_03","A114_04","A115_01",
  "A115_02","A115_03","A115_04","A116_01","A116_02","A116_03","A117_01","A117_02",
  "A117_03","A117_04","A117_05","A117_06","A117_07","A209_01","A209_02","A211",
  "A211_01","A211_02","A211_03","A211_04","A211_05","A211_06","A211_06a",
  "A212_01","A212_02","A212_03","A213_01","A213_02","A213_03","A213_04","A214_01",
  "A214_02","A214_03","A214_04","A215_01","A215_02","A215_03","A215_04","A216_01",
  "A216_02","A216_03","A217_01","A217_02","A217_03","A217_04","A217_05","A217_06",
  "A217_07","A310_01","A310_02","A311","A311_01","A311_02","A311_03","A311_04",
  "A311_05","A311_06","A311_06a","A312_01","A312_02","A312_03","A313_01",
  "A313_02","A313_03","A313_04","A314_01","A314_02","A314_03","A314_04","A315_01",
  "A315_02","A315_03","A315_04","A316_01","A316_02","A316_03","A317_01","A317_02",
  "A317_03","A317_04","A317_05","A317_06","A317_07","A401","A701_01","A702",
  "A702_05","A703","A705_01","D101_01","D101_02","D102","D102_01","D102_02",
  "D102_03","D102_04","D102_05","D102_06","D102_06a","D103_01","D103_02",
  "D103_03","D104_01","D104_02","D104_03","D104_04","D105_01","D105_02","D105_03",
  "D105_04","D106_01","D106_02","D106_03","D106_04","D107_01","D107_02","D107_03",
  "D108_01","D108_02","D108_03","D108_04","D108_05","D108_06","D108_07","D201_01",
  "D201_02","D202","D202_01","D202_02","D202_03","D202_04","D202_05","D202_06",
  "D202_06a","D203_01","D203_02","D203_03","D204_01","D204_02","D204_03",
  "D204_04","D205_01","D205_02","D205_03","D205_04","D206_01","D206_02","D206_03",
  "D206_04","D207_01","D207_02","D207_03","D208_01","D208_02","D208_03","D208_04",
  "D208_05","D208_06","D301_01","D301_02","D302","D302_01","D302_02","D302_03",
  "D302_04","D302_05","D302_06","D302_06a","D303_01","D303_02","D303_03",
  "D304_01","D304_02","D304_03","D304_04","D305_01","D305_02","D305_03","D305_04",
  "D306_01","D306_02","D306_03","D306_04","D307_01","D307_02","D307_03","D308_01",
  "D308_02","D308_03","D308_04","D308_05","D308_06","D401_01","D401_02","D402",
  "D402_01","D402_02","D402_03","D402_04","D402_05","D402_06","D402_06a",
  "D403_01","D403_02","D403_03","D404_01","D404_02","D404_03","D404_04","D405_01",
  "D405_02","D405_03","D405_04","D406_01","D406_02","D406_03","D406_04","D407_01",
  "D407_02","D407_03","D408_01","D408_02","D408_03","D408_04","D408_05","D408_06",
  "D501","D801_01","D802","D803","D804_01","RA01_CP","RA01","TIME001","TIME002",
  "TIME003","TIME004","TIME005","TIME006","TIME007","TIME008","TIME009","TIME010",
  "TIME011","TIME012","TIME013","TIME014","TIME015","TIME016","TIME017","TIME018",
  "TIME019","TIME020","TIME021","TIME022","TIME023","TIME024","TIME025",
  "TIME_SUM","MAILSENT","LASTDATA","STATUS","FINISHED","Q_VIEWER","LASTPAGE",
  "MAXPAGE","MISSING","MISSREL","TIME_RSI"
)

# 2. Read the XLSX file
# Note: skip = 1 is used if your Excel file has a descriptive text row in Row 1.
# If Row 1 is already the column headers, set skip = 0.
ds <- read_xlsx(
  path = "data_Carerobots_2026-01-20_09-51.xlsx", 
  sheet = 1, 
  col_names = col_names_vec,
  skip = 2 # second line is descriptive
)

# 3. Handle data types
# Loop through the map and apply transformations
for (col_name in names(type_map)) {
  if (col_name %in% names(ds)) {
    target_type <- type_map[col_name]
    
    if (target_type == "numeric") {
      ds[[col_name]] <- as.numeric(ds[[col_name]])
    } else if (target_type == "integer") {
      ds[[col_name]] <- as.integer(ds[[col_name]])
    } else if (target_type == "logical") {
      # Handle 'T'/'F' or 'TRUE'/'FALSE' strings
      ds[[col_name]] <- as.logical(ds[[col_name]])
    } else if (target_type == "POSIXct") {
      ds[[col_name]] <- as.POSIXct(ds[[col_name]])
    } else if (target_type == "factor") {
      ds[[col_name]] <- as.factor(ds[[col_name]])
    } else {
      ds[[col_name]] <- as.character(ds[[col_name]])
    }
  }
}

# Set row names
row.names(ds) <- ds$CASE

# 4. Set Metadata Attributes
attr(ds, "project")     <- "Carerobots"
attr(ds, "description") <- "Care Robots"
attr(ds, "date")        <- "2026-01-21 12:27:34"
attr(ds, "server")      <- "https://www.soscisurvey.de"


# Variable und Value Labels
ds$A401 = factor(ds$A401,
    levels=c("1","2","-9"),
    labels=c("Por la presente confirmo que he leído y entendido la información de participación descrita anteriormente y que estoy de acuerdo con las condiciones de participación.","No estoy de acuerdo con las condiciones de participación mencionadas anteriormente.","[NA] Not answered"),
    ordered=FALSE)
ds$A702 = factor(ds$A702,
    levels=c("1","2","3","4","5","-9"),
    labels=c("Mujer","Hombre","Diverso","Prefiere no decir","Prefiero describirme como:","[NA] Not answered"),
    ordered=FALSE)
ds$A703 = factor(ds$A703,
    levels=c("1","2","3","4","5","-9"),
    labels=c("1-5 años","5-10 años","10-15 años","15-20 años","más de 20 años","[NA] Not answered"),
    ordered=FALSE)
ds$D501 = factor(ds$D501,
    levels=c("1","2","-9"),
    labels=c("I hereby confirm that I have read and understood the participation information described above and that I agree to the conditions of participation.","I do not agree with the participation conditions mentioned above.","[NA] Not answered"),
    ordered=FALSE)
ds$D802 = factor(ds$D802,
    levels=c("1","2","3","4","5","-9"),
    labels=c("Female","Male","Diverse","Prefer not to say","I prefer to describe myself as:","[NA] Not answered"),
    ordered=FALSE)
ds$D803 = factor(ds$D803,
    levels=c("1","2","3","4","5","-9"),
    labels=c("1-5 years","5-10 years","10-15 years","15-20 years","more than 20 years","[NA] Not answered"),
    ordered=FALSE)
attr(ds$A011_01,"1") = "Totalmente en desacuerdo"
attr(ds$A011_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A011_01,"7") = "Totalmente de acuerdo"
attr(ds$A011_02,"1") = "Totalmente en desacuerdo"
attr(ds$A011_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A011_02,"7") = "Totalmente de acuerdo"
attr(ds$A012_01,"F") = "Not checked"
attr(ds$A012_01,"T") = "Checked"
attr(ds$A012_02,"F") = "Not checked"
attr(ds$A012_02,"T") = "Checked"
attr(ds$A012_03,"F") = "Not checked"
attr(ds$A012_03,"T") = "Checked"
attr(ds$A012_04,"F") = "Not checked"
attr(ds$A012_04,"T") = "Checked"
attr(ds$A012_05,"F") = "Not checked"
attr(ds$A012_05,"T") = "Checked"
attr(ds$A012_06,"F") = "Not checked"
attr(ds$A012_06,"T") = "Checked"
attr(ds$A015_01,"1") = "Totalmente en desacuerdo"
attr(ds$A015_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A015_01,"7") = "Totalmente de acuerdo"
attr(ds$A015_02,"1") = "Totalmente en desacuerdo"
attr(ds$A015_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A015_02,"7") = "Totalmente de acuerdo"
attr(ds$A015_03,"1") = "Totalmente en desacuerdo"
attr(ds$A015_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A015_03,"7") = "Totalmente de acuerdo"
attr(ds$A015_04,"1") = "Totalmente en desacuerdo"
attr(ds$A015_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A015_04,"7") = "Totalmente de acuerdo"
attr(ds$A016_01,"1") = "Totalmente en desacuerdo"
attr(ds$A016_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A016_01,"7") = "Totalmente de acuerdo"
attr(ds$A016_02,"1") = "Totalmente en desacuerdo"
attr(ds$A016_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A016_02,"7") = "Totalmente de acuerdo"
attr(ds$A016_03,"1") = "Totalmente en desacuerdo"
attr(ds$A016_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A016_03,"7") = "Totalmente de acuerdo"
attr(ds$A016_04,"1") = "Totalmente en desacuerdo"
attr(ds$A016_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A016_04,"7") = "Totalmente de acuerdo"
attr(ds$A017_01,"1") = "Totalmente en desacuerdo"
attr(ds$A017_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A017_01,"7") = "Totalmente de acuerdo"
attr(ds$A017_02,"1") = "Totalmente en desacuerdo"
attr(ds$A017_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A017_02,"7") = "Totalmente de acuerdo"
attr(ds$A017_03,"1") = "Totalmente en desacuerdo"
attr(ds$A017_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A017_03,"7") = "Totalmente de acuerdo"
attr(ds$A017_04,"1") = "Totalmente en desacuerdo"
attr(ds$A017_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A017_04,"7") = "Totalmente de acuerdo"
attr(ds$A018_01,"1") = "Totalmente en desacuerdo"
attr(ds$A018_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A018_01,"7") = "Totalmente de acuerdo"
attr(ds$A018_02,"1") = "Totalmente en desacuerdo"
attr(ds$A018_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A018_02,"7") = "Totalmente de acuerdo"
attr(ds$A018_03,"1") = "Totalmente en desacuerdo"
attr(ds$A018_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A018_03,"7") = "Totalmente de acuerdo"
attr(ds$A019_01,"1") = "Poco ético"
attr(ds$A019_01,"7") = "Ético"
attr(ds$A019_02,"1") = "Injusto"
attr(ds$A019_02,"7") = "Justo"
attr(ds$A019_03,"1") = "No es moralmente correcto"
attr(ds$A019_03,"7") = "Moralmente correcto"
attr(ds$A019_04,"1") = "No aceptable para mi familia"
attr(ds$A019_04,"7") = "Aceptable para mi familia"
attr(ds$A019_05,"1") = "Culturalmente inaceptable"
attr(ds$A019_05,"7") = "Culturalmente aceptable"
attr(ds$A019_06,"1") = "No es personalmente satisfactorio"
attr(ds$A019_06,"7") = "Personalmente satisfactorio"
attr(ds$A019_07,"1") = "Viola un contrato tácito"
attr(ds$A019_07,"7") = "No viola un contrato tácito"
attr(ds$A110_01,"1") = "Totalmente en desacuerdo"
attr(ds$A110_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A110_01,"7") = "Totalmente de acuerdo"
attr(ds$A110_02,"1") = "Totalmente en desacuerdo"
attr(ds$A110_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A110_02,"7") = "Totalmente de acuerdo"
attr(ds$A111_01,"F") = "Not checked"
attr(ds$A111_01,"T") = "Checked"
attr(ds$A111_02,"F") = "Not checked"
attr(ds$A111_02,"T") = "Checked"
attr(ds$A111_03,"F") = "Not checked"
attr(ds$A111_03,"T") = "Checked"
attr(ds$A111_04,"F") = "Not checked"
attr(ds$A111_04,"T") = "Checked"
attr(ds$A111_05,"F") = "Not checked"
attr(ds$A111_05,"T") = "Checked"
attr(ds$A111_06,"F") = "Not checked"
attr(ds$A111_06,"T") = "Checked"
attr(ds$A113_01,"1") = "Totalmente en desacuerdo"
attr(ds$A113_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A113_01,"7") = "Totalmente de acuerdo"
attr(ds$A113_02,"1") = "Totalmente en desacuerdo"
attr(ds$A113_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A113_02,"7") = "Totalmente de acuerdo"
attr(ds$A113_03,"1") = "Totalmente en desacuerdo"
attr(ds$A113_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A113_03,"7") = "Totalmente de acuerdo"
attr(ds$A113_04,"1") = "Totalmente en desacuerdo"
attr(ds$A113_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A113_04,"7") = "Totalmente de acuerdo"
attr(ds$A114_01,"1") = "Totalmente en desacuerdo"
attr(ds$A114_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A114_01,"7") = "Totalmente de acuerdo"
attr(ds$A114_02,"1") = "Totalmente en desacuerdo"
attr(ds$A114_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A114_02,"7") = "Totalmente de acuerdo"
attr(ds$A114_03,"1") = "Totalmente en desacuerdo"
attr(ds$A114_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A114_03,"7") = "Totalmente de acuerdo"
attr(ds$A114_04,"1") = "Totalmente en desacuerdo"
attr(ds$A114_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A114_04,"7") = "Totalmente de acuerdo"
attr(ds$A115_01,"1") = "Totalmente en desacuerdo"
attr(ds$A115_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A115_01,"7") = "Totalmente de acuerdo"
attr(ds$A115_02,"1") = "Totalmente en desacuerdo"
attr(ds$A115_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A115_02,"7") = "Totalmente de acuerdo"
attr(ds$A115_03,"1") = "Totalmente en desacuerdo"
attr(ds$A115_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A115_03,"7") = "Totalmente de acuerdo"
attr(ds$A115_04,"1") = "Totalmente en desacuerdo"
attr(ds$A115_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A115_04,"7") = "Totalmente de acuerdo"
attr(ds$A116_01,"1") = "Totalmente en desacuerdo"
attr(ds$A116_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A116_01,"7") = "Totalmente de acuerdo"
attr(ds$A116_02,"1") = "Totalmente en desacuerdo"
attr(ds$A116_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A116_02,"7") = "Totalmente de acuerdo"
attr(ds$A116_03,"1") = "Totalmente en desacuerdo"
attr(ds$A116_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A116_03,"7") = "Totalmente de acuerdo"
attr(ds$A117_01,"1") = "Poco ético"
attr(ds$A117_01,"7") = "Ético"
attr(ds$A117_02,"1") = "Injusto"
attr(ds$A117_02,"7") = "Justo"
attr(ds$A117_03,"1") = "No es moralmente correcto"
attr(ds$A117_03,"7") = "Moralmente correcto"
attr(ds$A117_04,"1") = "No aceptable para mi familia"
attr(ds$A117_04,"7") = "Aceptable para mi familia"
attr(ds$A117_05,"1") = "Culturalmente inaceptable"
attr(ds$A117_05,"7") = "Culturalmente aceptable"
attr(ds$A117_06,"1") = "No es personalmente satisfactorio"
attr(ds$A117_06,"7") = "Personalmente satisfactorio"
attr(ds$A117_07,"1") = "Viola un contrato tácito"
attr(ds$A117_07,"7") = "No viola un contrato tácito"
attr(ds$A209_01,"1") = "Totalmente en desacuerdo"
attr(ds$A209_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A209_01,"7") = "Totalmente de acuerdo"
attr(ds$A209_02,"1") = "Totalmente en desacuerdo"
attr(ds$A209_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A209_02,"7") = "Totalmente de acuerdo"
attr(ds$A211_01,"F") = "Not checked"
attr(ds$A211_01,"T") = "Checked"
attr(ds$A211_02,"F") = "Not checked"
attr(ds$A211_02,"T") = "Checked"
attr(ds$A211_03,"F") = "Not checked"
attr(ds$A211_03,"T") = "Checked"
attr(ds$A211_04,"F") = "Not checked"
attr(ds$A211_04,"T") = "Checked"
attr(ds$A211_05,"F") = "Not checked"
attr(ds$A211_05,"T") = "Checked"
attr(ds$A211_06,"F") = "Not checked"
attr(ds$A211_06,"T") = "Checked"
attr(ds$A213_01,"1") = "Totalmente en desacuerdo"
attr(ds$A213_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A213_01,"7") = "Totalmente de acuerdo"
attr(ds$A213_02,"1") = "Totalmente en desacuerdo"
attr(ds$A213_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A213_02,"7") = "Totalmente de acuerdo"
attr(ds$A213_03,"1") = "Totalmente en desacuerdo"
attr(ds$A213_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A213_03,"7") = "Totalmente de acuerdo"
attr(ds$A213_04,"1") = "Totalmente en desacuerdo"
attr(ds$A213_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A213_04,"7") = "Totalmente de acuerdo"
attr(ds$A214_01,"1") = "Totalmente en desacuerdo"
attr(ds$A214_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A214_01,"7") = "Totalmente de acuerdo"
attr(ds$A214_02,"1") = "Totalmente en desacuerdo"
attr(ds$A214_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A214_02,"7") = "Totalmente de acuerdo"
attr(ds$A214_03,"1") = "Totalmente en desacuerdo"
attr(ds$A214_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A214_03,"7") = "Totalmente de acuerdo"
attr(ds$A214_04,"1") = "Totalmente en desacuerdo"
attr(ds$A214_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A214_04,"7") = "Totalmente de acuerdo"
attr(ds$A215_01,"1") = "Totalmente en desacuerdo"
attr(ds$A215_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A215_01,"7") = "Totalmente de acuerdo"
attr(ds$A215_02,"1") = "Totalmente en desacuerdo"
attr(ds$A215_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A215_02,"7") = "Totalmente de acuerdo"
attr(ds$A215_03,"1") = "Totalmente en desacuerdo"
attr(ds$A215_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A215_03,"7") = "Totalmente de acuerdo"
attr(ds$A215_04,"1") = "Totalmente en desacuerdo"
attr(ds$A215_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A215_04,"7") = "Totalmente de acuerdo"
attr(ds$A216_01,"1") = "Totalmente en desacuerdo"
attr(ds$A216_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A216_01,"7") = "Totalmente de acuerdo"
attr(ds$A216_02,"1") = "Totalmente en desacuerdo"
attr(ds$A216_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A216_02,"7") = "Totalmente de acuerdo"
attr(ds$A216_03,"1") = "Totalmente en desacuerdo"
attr(ds$A216_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A216_03,"7") = "Totalmente de acuerdo"
attr(ds$A217_01,"1") = "Poco ético"
attr(ds$A217_01,"7") = "Ético"
attr(ds$A217_02,"1") = "Injusto"
attr(ds$A217_02,"7") = "Justo"
attr(ds$A217_03,"1") = "No es moralmente correcto"
attr(ds$A217_03,"7") = "Moralmente correcto"
attr(ds$A217_04,"1") = "No aceptable para mi familia"
attr(ds$A217_04,"7") = "Aceptable para mi familia"
attr(ds$A217_05,"1") = "Culturalmente inaceptable"
attr(ds$A217_05,"7") = "Culturalmente aceptable"
attr(ds$A217_06,"1") = "No es personalmente satisfactorio"
attr(ds$A217_06,"7") = "Personalmente satisfactorio"
attr(ds$A217_07,"1") = "Viola un contrato tácito"
attr(ds$A217_07,"7") = "No viola un contrato tácito"
attr(ds$A310_01,"1") = "Totalmente en desacuerdo"
attr(ds$A310_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A310_01,"7") = "Totalmente de acuerdo"
attr(ds$A310_02,"1") = "Totalmente en desacuerdo"
attr(ds$A310_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A310_02,"7") = "Totalmente de acuerdo"
attr(ds$A311_01,"F") = "Not checked"
attr(ds$A311_01,"T") = "Checked"
attr(ds$A311_02,"F") = "Not checked"
attr(ds$A311_02,"T") = "Checked"
attr(ds$A311_03,"F") = "Not checked"
attr(ds$A311_03,"T") = "Checked"
attr(ds$A311_04,"F") = "Not checked"
attr(ds$A311_04,"T") = "Checked"
attr(ds$A311_05,"F") = "Not checked"
attr(ds$A311_05,"T") = "Checked"
attr(ds$A311_06,"F") = "Not checked"
attr(ds$A311_06,"T") = "Checked"
attr(ds$A313_01,"1") = "Totalmente en desacuerdo"
attr(ds$A313_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A313_01,"7") = "Totalmente de acuerdo"
attr(ds$A313_02,"1") = "Totalmente en desacuerdo"
attr(ds$A313_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A313_02,"7") = "Totalmente de acuerdo"
attr(ds$A313_03,"1") = "Totalmente en desacuerdo"
attr(ds$A313_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A313_03,"7") = "Totalmente de acuerdo"
attr(ds$A313_04,"1") = "Totalmente en desacuerdo"
attr(ds$A313_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A313_04,"7") = "Totalmente de acuerdo"
attr(ds$A314_01,"1") = "Totalmente en desacuerdo"
attr(ds$A314_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A314_01,"7") = "Totalmente de acuerdo"
attr(ds$A314_02,"1") = "Totalmente en desacuerdo"
attr(ds$A314_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A314_02,"7") = "Totalmente de acuerdo"
attr(ds$A314_03,"1") = "Totalmente en desacuerdo"
attr(ds$A314_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A314_03,"7") = "Totalmente de acuerdo"
attr(ds$A314_04,"1") = "Totalmente en desacuerdo"
attr(ds$A314_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A314_04,"7") = "Totalmente de acuerdo"
attr(ds$A315_01,"1") = "Totalmente en desacuerdo"
attr(ds$A315_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A315_01,"7") = "Totalmente de acuerdo"
attr(ds$A315_02,"1") = "Totalmente en desacuerdo"
attr(ds$A315_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A315_02,"7") = "Totalmente de acuerdo"
attr(ds$A315_03,"1") = "Totalmente en desacuerdo"
attr(ds$A315_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A315_03,"7") = "Totalmente de acuerdo"
attr(ds$A315_04,"1") = "Totalmente en desacuerdo"
attr(ds$A315_04,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A315_04,"7") = "Totalmente de acuerdo"
attr(ds$A316_01,"1") = "Totalmente en desacuerdo"
attr(ds$A316_01,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A316_01,"7") = "Totalmente de acuerdo"
attr(ds$A316_02,"1") = "Totalmente en desacuerdo"
attr(ds$A316_02,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A316_02,"7") = "Totalmente de acuerdo"
attr(ds$A316_03,"1") = "Totalmente en desacuerdo"
attr(ds$A316_03,"4") = "Ni de acuerdo ni en desacuerdo"
attr(ds$A316_03,"7") = "Totalmente de acuerdo"
attr(ds$A317_01,"1") = "Poco ético"
attr(ds$A317_01,"7") = "Ético"
attr(ds$A317_02,"1") = "Injusto"
attr(ds$A317_02,"7") = "Justo"
attr(ds$A317_03,"1") = "No es moralmente correcto"
attr(ds$A317_03,"7") = "Moralmente correcto"
attr(ds$A317_04,"1") = "No aceptable para mi familia"
attr(ds$A317_04,"7") = "Aceptable para mi familia"
attr(ds$A317_05,"1") = "Culturalmente inaceptable"
attr(ds$A317_05,"7") = "Culturalmente aceptable"
attr(ds$A317_06,"1") = "No es personalmente satisfactorio"
attr(ds$A317_06,"7") = "Personalmente satisfactorio"
attr(ds$A317_07,"1") = "Viola un contrato tácito"
attr(ds$A317_07,"7") = "No viola un contrato tácito"
attr(ds$D101_01,"1") = "Strongly disagree"
attr(ds$D101_01,"4") = "Neither agree nor disagree"
attr(ds$D101_01,"7") = "Strongly agree"
attr(ds$D101_02,"1") = "Strongly disagree"
attr(ds$D101_02,"4") = "Neither agree nor disagree"
attr(ds$D101_02,"7") = "Strongly agree"
attr(ds$D102_01,"F") = "Not checked"
attr(ds$D102_01,"T") = "Checked"
attr(ds$D102_02,"F") = "Not checked"
attr(ds$D102_02,"T") = "Checked"
attr(ds$D102_03,"F") = "Not checked"
attr(ds$D102_03,"T") = "Checked"
attr(ds$D102_04,"F") = "Not checked"
attr(ds$D102_04,"T") = "Checked"
attr(ds$D102_05,"F") = "Not checked"
attr(ds$D102_05,"T") = "Checked"
attr(ds$D102_06,"F") = "Not checked"
attr(ds$D102_06,"T") = "Checked"
attr(ds$D104_01,"1") = "Strongly disagree"
attr(ds$D104_01,"4") = "Neither agree nor disagree"
attr(ds$D104_01,"7") = "Strongly agree"
attr(ds$D104_02,"1") = "Strongly disagree"
attr(ds$D104_02,"4") = "Neither agree nor disagree"
attr(ds$D104_02,"7") = "Strongly agree"
attr(ds$D104_03,"1") = "Strongly disagree"
attr(ds$D104_03,"4") = "Neither agree nor disagree"
attr(ds$D104_03,"7") = "Strongly agree"
attr(ds$D104_04,"1") = "Strongly disagree"
attr(ds$D104_04,"4") = "Neither agree nor disagree"
attr(ds$D104_04,"7") = "Strongly agree"
attr(ds$D105_01,"1") = "Strongly disagree"
attr(ds$D105_01,"4") = "Neither agree nor disagree"
attr(ds$D105_01,"7") = "Strongly agree"
attr(ds$D105_02,"1") = "Strongly disagree"
attr(ds$D105_02,"4") = "Neither agree nor disagree"
attr(ds$D105_02,"7") = "Strongly agree"
attr(ds$D105_03,"1") = "Strongly disagree"
attr(ds$D105_03,"4") = "Neither agree nor disagree"
attr(ds$D105_03,"7") = "Strongly agree"
attr(ds$D105_04,"1") = "Strongly disagree"
attr(ds$D105_04,"4") = "Neither agree nor disagree"
attr(ds$D105_04,"7") = "Strongly agree"
attr(ds$D106_01,"1") = "Strongly disagree"
attr(ds$D106_01,"4") = "Neither agree nor disagree"
attr(ds$D106_01,"7") = "Strongly agree"
attr(ds$D106_02,"1") = "Strongly disagree"
attr(ds$D106_02,"4") = "Neither agree nor disagree"
attr(ds$D106_02,"7") = "Strongly agree"
attr(ds$D106_03,"1") = "Strongly disagree"
attr(ds$D106_03,"4") = "Neither agree nor disagree"
attr(ds$D106_03,"7") = "Strongly agree"
attr(ds$D106_04,"1") = "Strongly disagree"
attr(ds$D106_04,"4") = "Neither agree nor disagree"
attr(ds$D106_04,"7") = "Strongly agree"
attr(ds$D107_01,"1") = "Strongly disagree"
attr(ds$D107_01,"4") = "Neither agree nor disagree"
attr(ds$D107_01,"7") = "Strongly agree"
attr(ds$D107_02,"1") = "Strongly disagree"
attr(ds$D107_02,"4") = "Neither agree nor disagree"
attr(ds$D107_02,"7") = "Strongly agree"
attr(ds$D107_03,"1") = "Strongly disagree"
attr(ds$D107_03,"4") = "Neither agree nor disagree"
attr(ds$D107_03,"7") = "Strongly agree"
attr(ds$D108_01,"1") = "Unethical"
attr(ds$D108_01,"5") = "Ethical"
attr(ds$D108_02,"1") = "Unfair"
attr(ds$D108_02,"5") = "Fair"
attr(ds$D108_03,"1") = "Not morally right"
attr(ds$D108_03,"5") = "Morally right"
attr(ds$D108_04,"1") = "Not acceptable to my family"
attr(ds$D108_04,"5") = "Acceptable to my family"
attr(ds$D108_05,"1") = "Culturally unacceptable"
attr(ds$D108_05,"5") = "Culturally acceptable"
attr(ds$D108_06,"1") = "Not personally satisfying"
attr(ds$D108_06,"5") = "Personally satisfying"
attr(ds$D108_07,"1") = "Violates an unwritten contract"
attr(ds$D108_07,"5") = "Does not violate an unwritten contract"
attr(ds$D201_01,"1") = "Strongly disagree"
attr(ds$D201_01,"4") = "Neither agree nor disagree"
attr(ds$D201_01,"7") = "Strongly agree"
attr(ds$D201_02,"1") = "Strongly disagree"
attr(ds$D201_02,"4") = "Neither agree nor disagree"
attr(ds$D201_02,"7") = "Strongly agree"
attr(ds$D202_01,"F") = "Not checked"
attr(ds$D202_01,"T") = "Checked"
attr(ds$D202_02,"F") = "Not checked"
attr(ds$D202_02,"T") = "Checked"
attr(ds$D202_03,"F") = "Not checked"
attr(ds$D202_03,"T") = "Checked"
attr(ds$D202_04,"F") = "Not checked"
attr(ds$D202_04,"T") = "Checked"
attr(ds$D202_05,"F") = "Not checked"
attr(ds$D202_05,"T") = "Checked"
attr(ds$D202_06,"F") = "Not checked"
attr(ds$D202_06,"T") = "Checked"
attr(ds$D204_01,"1") = "Strongly disagree"
attr(ds$D204_01,"4") = "Neither agree nor disagree"
attr(ds$D204_01,"7") = "Strongly agree"
attr(ds$D204_02,"1") = "Strongly disagree"
attr(ds$D204_02,"4") = "Neither agree nor disagree"
attr(ds$D204_02,"7") = "Strongly agree"
attr(ds$D204_03,"1") = "Strongly disagree"
attr(ds$D204_03,"4") = "Neither agree nor disagree"
attr(ds$D204_03,"7") = "Strongly agree"
attr(ds$D204_04,"1") = "Strongly disagree"
attr(ds$D204_04,"4") = "Neither agree nor disagree"
attr(ds$D204_04,"7") = "Strongly agree"
attr(ds$D205_01,"1") = "Strongly disagree"
attr(ds$D205_01,"4") = "Neither agree nor disagree"
attr(ds$D205_01,"7") = "Strongly agree"
attr(ds$D205_02,"1") = "Strongly disagree"
attr(ds$D205_02,"4") = "Neither agree nor disagree"
attr(ds$D205_02,"7") = "Strongly agree"
attr(ds$D205_03,"1") = "Strongly disagree"
attr(ds$D205_03,"4") = "Neither agree nor disagree"
attr(ds$D205_03,"7") = "Strongly agree"
attr(ds$D205_04,"1") = "Strongly disagree"
attr(ds$D205_04,"4") = "Neither agree nor disagree"
attr(ds$D205_04,"7") = "Strongly agree"
attr(ds$D206_01,"1") = "Strongly disagree"
attr(ds$D206_01,"4") = "Neither agree nor disagree"
attr(ds$D206_01,"7") = "Strongly agree"
attr(ds$D206_02,"1") = "Strongly disagree"
attr(ds$D206_02,"4") = "Neither agree nor disagree"
attr(ds$D206_02,"7") = "Strongly agree"
attr(ds$D206_03,"1") = "Strongly disagree"
attr(ds$D206_03,"4") = "Neither agree nor disagree"
attr(ds$D206_03,"7") = "Strongly agree"
attr(ds$D206_04,"1") = "Strongly disagree"
attr(ds$D206_04,"4") = "Neither agree nor disagree"
attr(ds$D206_04,"7") = "Strongly agree"
attr(ds$D207_01,"1") = "Strongly disagree"
attr(ds$D207_01,"4") = "Neither agree nor disagree"
attr(ds$D207_01,"7") = "Strongly agree"
attr(ds$D207_02,"1") = "Strongly disagree"
attr(ds$D207_02,"4") = "Neither agree nor disagree"
attr(ds$D207_02,"7") = "Strongly agree"
attr(ds$D207_03,"1") = "Strongly disagree"
attr(ds$D207_03,"4") = "Neither agree nor disagree"
attr(ds$D207_03,"7") = "Strongly agree"
attr(ds$D208_01,"1") = "Unethical"
attr(ds$D208_01,"5") = "Ethical"
attr(ds$D208_02,"1") = "Unfair"
attr(ds$D208_02,"5") = "Fair"
attr(ds$D208_03,"1") = "Not acceptable to my family"
attr(ds$D208_03,"5") = "Acceptable to my family"
attr(ds$D208_04,"1") = "Culturally unacceptable"
attr(ds$D208_04,"5") = "Culturally acceptable"
attr(ds$D208_05,"1") = "Not personally satisfying"
attr(ds$D208_05,"5") = "Personally satisfying"
attr(ds$D208_06,"1") = "Violates an unwritten contract"
attr(ds$D208_06,"5") = "Does not violate an unwritten contract"
attr(ds$D301_01,"1") = "Strongly disagree"
attr(ds$D301_01,"4") = "Neither agree nor disagree"
attr(ds$D301_01,"7") = "Strongly agree"
attr(ds$D301_02,"1") = "Strongly disagree"
attr(ds$D301_02,"4") = "Neither agree nor disagree"
attr(ds$D301_02,"7") = "Strongly agree"
attr(ds$D302_01,"F") = "Not checked"
attr(ds$D302_01,"T") = "Checked"
attr(ds$D302_02,"F") = "Not checked"
attr(ds$D302_02,"T") = "Checked"
attr(ds$D302_03,"F") = "Not checked"
attr(ds$D302_03,"T") = "Checked"
attr(ds$D302_04,"F") = "Not checked"
attr(ds$D302_04,"T") = "Checked"
attr(ds$D302_05,"F") = "Not checked"
attr(ds$D302_05,"T") = "Checked"
attr(ds$D302_06,"F") = "Not checked"
attr(ds$D302_06,"T") = "Checked"
attr(ds$D304_01,"1") = "Strongly disagree"
attr(ds$D304_01,"4") = "Neither agree nor disagree"
attr(ds$D304_01,"7") = "Strongly agree"
attr(ds$D304_02,"1") = "Strongly disagree"
attr(ds$D304_02,"4") = "Neither agree nor disagree"
attr(ds$D304_02,"7") = "Strongly agree"
attr(ds$D304_03,"1") = "Strongly disagree"
attr(ds$D304_03,"4") = "Neither agree nor disagree"
attr(ds$D304_03,"7") = "Strongly agree"
attr(ds$D304_04,"1") = "Strongly disagree"
attr(ds$D304_04,"4") = "Neither agree nor disagree"
attr(ds$D304_04,"7") = "Strongly agree"
attr(ds$D305_01,"1") = "Strongly disagree"
attr(ds$D305_01,"4") = "Neither agree nor disagree"
attr(ds$D305_01,"7") = "Strongly agree"
attr(ds$D305_02,"1") = "Strongly disagree"
attr(ds$D305_02,"4") = "Neither agree nor disagree"
attr(ds$D305_02,"7") = "Strongly agree"
attr(ds$D305_03,"1") = "Strongly disagree"
attr(ds$D305_03,"4") = "Neither agree nor disagree"
attr(ds$D305_03,"7") = "Strongly agree"
attr(ds$D305_04,"1") = "Strongly disagree"
attr(ds$D305_04,"4") = "Neither agree nor disagree"
attr(ds$D305_04,"7") = "Strongly agree"
attr(ds$D306_01,"1") = "Strongly disagree"
attr(ds$D306_01,"4") = "Neither agree nor disagree"
attr(ds$D306_01,"7") = "Strongly agree"
attr(ds$D306_02,"1") = "Strongly disagree"
attr(ds$D306_02,"4") = "Neither agree nor disagree"
attr(ds$D306_02,"7") = "Strongly agree"
attr(ds$D306_03,"1") = "Strongly disagree"
attr(ds$D306_03,"4") = "Neither agree nor disagree"
attr(ds$D306_03,"7") = "Strongly agree"
attr(ds$D306_04,"1") = "Strongly disagree"
attr(ds$D306_04,"4") = "Neither agree nor disagree"
attr(ds$D306_04,"7") = "Strongly agree"
attr(ds$D307_01,"1") = "Strongly disagree"
attr(ds$D307_01,"4") = "Neither agree nor disagree"
attr(ds$D307_01,"7") = "Strongly agree"
attr(ds$D307_02,"1") = "Strongly disagree"
attr(ds$D307_02,"4") = "Neither agree nor disagree"
attr(ds$D307_02,"7") = "Strongly agree"
attr(ds$D307_03,"1") = "Strongly disagree"
attr(ds$D307_03,"4") = "Neither agree nor disagree"
attr(ds$D307_03,"7") = "Strongly agree"
attr(ds$D308_01,"1") = "Unethical"
attr(ds$D308_01,"5") = "Ethical"
attr(ds$D308_02,"1") = "Unfair"
attr(ds$D308_02,"5") = "Fair"
attr(ds$D308_03,"1") = "Not acceptable to my family"
attr(ds$D308_03,"5") = "Acceptable to my family"
attr(ds$D308_04,"1") = "Culturally unacceptable"
attr(ds$D308_04,"5") = "Culturally acceptable"
attr(ds$D308_05,"1") = "Not personally satisfying"
attr(ds$D308_05,"5") = "Personally satisfying"
attr(ds$D308_06,"1") = "Violates an unwritten contract"
attr(ds$D308_06,"5") = "Does not violate an unwritten contract"
attr(ds$D401_01,"1") = "Strongly disagree"
attr(ds$D401_01,"4") = "Neither agree nor disagree"
attr(ds$D401_01,"7") = "Strongly agree"
attr(ds$D401_02,"1") = "Strongly disagree"
attr(ds$D401_02,"4") = "Neither agree nor disagree"
attr(ds$D401_02,"7") = "Strongly agree"
attr(ds$D402_01,"F") = "Not checked"
attr(ds$D402_01,"T") = "Checked"
attr(ds$D402_02,"F") = "Not checked"
attr(ds$D402_02,"T") = "Checked"
attr(ds$D402_03,"F") = "Not checked"
attr(ds$D402_03,"T") = "Checked"
attr(ds$D402_04,"F") = "Not checked"
attr(ds$D402_04,"T") = "Checked"
attr(ds$D402_05,"F") = "Not checked"
attr(ds$D402_05,"T") = "Checked"
attr(ds$D402_06,"F") = "Not checked"
attr(ds$D402_06,"T") = "Checked"
attr(ds$D404_01,"1") = "Strongly disagree"
attr(ds$D404_01,"4") = "Neither agree nor disagree"
attr(ds$D404_01,"7") = "Strongly agree"
attr(ds$D404_02,"1") = "Strongly disagree"
attr(ds$D404_02,"4") = "Neither agree nor disagree"
attr(ds$D404_02,"7") = "Strongly agree"
attr(ds$D404_03,"1") = "Strongly disagree"
attr(ds$D404_03,"4") = "Neither agree nor disagree"
attr(ds$D404_03,"7") = "Strongly agree"
attr(ds$D404_04,"1") = "Strongly disagree"
attr(ds$D404_04,"4") = "Neither agree nor disagree"
attr(ds$D404_04,"7") = "Strongly agree"
attr(ds$D405_01,"1") = "Strongly disagree"
attr(ds$D405_01,"4") = "Neither agree nor disagree"
attr(ds$D405_01,"7") = "Strongly agree"
attr(ds$D405_02,"1") = "Strongly disagree"
attr(ds$D405_02,"4") = "Neither agree nor disagree"
attr(ds$D405_02,"7") = "Strongly agree"
attr(ds$D405_03,"1") = "Strongly disagree"
attr(ds$D405_03,"4") = "Neither agree nor disagree"
attr(ds$D405_03,"7") = "Strongly agree"
attr(ds$D405_04,"1") = "Strongly disagree"
attr(ds$D405_04,"4") = "Neither agree nor disagree"
attr(ds$D405_04,"7") = "Strongly agree"
attr(ds$D406_01,"1") = "Strongly disagree"
attr(ds$D406_01,"4") = "Neither agree nor disagree"
attr(ds$D406_01,"7") = "Strongly agree"
attr(ds$D406_02,"1") = "Strongly disagree"
attr(ds$D406_02,"4") = "Neither agree nor disagree"
attr(ds$D406_02,"7") = "Strongly agree"
attr(ds$D406_03,"1") = "Strongly disagree"
attr(ds$D406_03,"4") = "Neither agree nor disagree"
attr(ds$D406_03,"7") = "Strongly agree"
attr(ds$D406_04,"1") = "Strongly disagree"
attr(ds$D406_04,"4") = "Neither agree nor disagree"
attr(ds$D406_04,"7") = "Strongly agree"
attr(ds$D407_01,"1") = "Strongly disagree"
attr(ds$D407_01,"4") = "Neither agree nor disagree"
attr(ds$D407_01,"7") = "Strongly agree"
attr(ds$D407_02,"1") = "Strongly disagree"
attr(ds$D407_02,"4") = "Neither agree nor disagree"
attr(ds$D407_02,"7") = "Strongly agree"
attr(ds$D407_03,"1") = "Strongly disagree"
attr(ds$D407_03,"4") = "Neither agree nor disagree"
attr(ds$D407_03,"7") = "Strongly agree"
attr(ds$D408_01,"1") = "Unethical"
attr(ds$D408_01,"5") = "Ethical"
attr(ds$D408_02,"1") = "Unfair"
attr(ds$D408_02,"5") = "Fair"
attr(ds$D408_03,"1") = "Not acceptable to my family"
attr(ds$D408_03,"5") = "Acceptable to my family"
attr(ds$D408_04,"1") = "Culturally unacceptable"
attr(ds$D408_04,"5") = "Culturally acceptable"
attr(ds$D408_05,"1") = "Not personally satisfying"
attr(ds$D408_05,"5") = "Personally satisfying"
attr(ds$D408_06,"1") = "Violates an unwritten contract"
attr(ds$D408_06,"5") = "Does not violate an unwritten contract"
attr(ds$RA01,"1") = "B5-B9, B10-B14, B15-B19, B20-B24"
attr(ds$RA01,"2") = "B5-B9, B10-B14, B20-B24, B15-B19"
attr(ds$RA01,"3") = "B5-B9, B15-B19, B10-B14, B20-B24"
attr(ds$RA01,"4") = "B5-B9, B15-B19, B20-B24, B10-B14"
attr(ds$RA01,"5") = "B5-B9, B20-B24, B10-B14, B15-B19"
attr(ds$RA01,"6") = "B5-B9, B20-B24, B15-B19, B10-B14"
attr(ds$RA01,"7") = "B10-B14, B5-B9, B15-B19, B20-B24"
attr(ds$RA01,"8") = "B10-B14, B5-B9, B20-B24, B15-B19"
attr(ds$RA01,"9") = "B10-B14, B15-B19, B5-B9, B20-B24"
attr(ds$RA01,"10") = "B10-B14, B15-B19, B20-B24, B5-B9"
attr(ds$RA01,"11") = "B10-B14, B20-B24, B5-B9, B15-B19"
attr(ds$RA01,"12") = "B10-B14, B20-B24, B15-B19, B5-B9"
attr(ds$RA01,"13") = "B15-B19, B5-B9, B10-B14, B20-B24"
attr(ds$RA01,"14") = "B15-B19, B5-B9, B20-B24, B10-B14"
attr(ds$RA01,"15") = "B15-B19, B10-B14, B5-B9, B20-B24"
attr(ds$RA01,"16") = "B15-B19, B10-B14, B20-B24, B5-B9"
attr(ds$RA01,"17") = "B15-B19, B20-B24, B5-B9, B10-B14"
attr(ds$RA01,"18") = "B15-B19, B20-B24, B10-B14, B5-B9"
attr(ds$RA01,"19") = "B20-B24, B5-B9, B10-B14, B15-B19"
attr(ds$RA01,"20") = "B20-B24, B5-B9, B15-B19, B10-B14"
attr(ds$RA01,"21") = "B20-B24, B10-B14, B5-B9, B15-B19"
attr(ds$RA01,"22") = "B20-B24, B10-B14, B15-B19, B5-B9"
attr(ds$RA01,"23") = "B20-B24, B15-B19, B5-B9, B10-B14"
attr(ds$RA01,"24") = "B20-B24, B15-B19, B10-B14, B5-B9"
attr(ds$STATUS,"complete") = "Complete case"
attr(ds$STATUS,"finished") = "Interview finished (got to last page)"
attr(ds$STATUS,"quality fail") = "Flagged as invalid record"
attr(ds$STATUS,"quota full") = "Rejected due to quota stop"
attr(ds$STATUS,"screenout") = "Rejected due to screening criteria"
attr(ds$FINISHED,"F") = "Canceled"
attr(ds$FINISHED,"T") = "Finished"
attr(ds$Q_VIEWER,"F") = "Respondent"
attr(ds$Q_VIEWER,"T") = "Spectator"
comment(ds$SERIAL) = "Serial number (if provided)"
comment(ds$REF) = "Reference (if provided in link)"
comment(ds$QUESTNNR) = "Questionnaire that has been used in the interview"
comment(ds$MODE) = "Interview mode"
comment(ds$STARTED) = "Time the interview has started (Europe/Berlin)"
comment(ds$A011_01) = "General Rating: En general, calificaría al robot de manera positiva"
comment(ds$A011_02) = "General Rating: En general, apoyaría la integración de este robot en entornos de atención médica"
comment(ds$A012) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$A012_01) = "Use of Robots in Medical Settings: Hospitales Generales"
comment(ds$A012_02) = "Use of Robots in Medical Settings: Hospitales Pediátricos"
comment(ds$A012_03) = "Use of Robots in Medical Settings: Hospitales Geriátricos"
comment(ds$A012_04) = "Use of Robots in Medical Settings: Hospitales Psiquiátricos"
comment(ds$A012_05) = "Use of Robots in Medical Settings: Hospitales de traumatología y ortopedia"
comment(ds$A012_06) = "Use of Robots in Medical Settings: Otro campo, ¿cuál?"
comment(ds$A012_06a) = "Use of Robots in Medical Settings: Otro campo, ¿cuál? (free text)"
comment(ds$A014_01) = "Open Questions: ¿Cuáles son sus principales razones para aceptar o rechazar el uso de este robot en tareas de cuidado? Puede referirse a situaciones específicas, sentimientos o expectativas que tenga"
comment(ds$A014_02) = "Open Questions: ¿Ve algún riesgo o preocupación ética en el uso de este robot en el ámbito de la salud? Por favor, explíque su respuesta"
comment(ds$A014_03) = "Open Questions: Según su experiencia profesional, ¿qué cuestiones éticas cree que deberían considerarse al desarrollar o implementar este robot?"
comment(ds$A015_01) = "Performance Expectancy (PE): Consideraría útil al robot en mi trabajo."
comment(ds$A015_02) = "Performance Expectancy (PE): Usar el robot me permitiría realizar las tareas más rápidamente."
comment(ds$A015_03) = "Performance Expectancy (PE): Usar el robot aumentaría mi productividad."
comment(ds$A015_04) = "Performance Expectancy (PE): Si usara el robot, tendría más posibilidades de recibir un aumento."
comment(ds$A016_01) = "Attitude Toward using Technology: Mi interacción con el robot sería clara y comprensible."
comment(ds$A016_02) = "Attitude Toward using Technology: El robot haría que el trabajo fuera más interesante."
comment(ds$A016_03) = "Attitude Toward using Technology: Trabajar con el robot sería divertido."
comment(ds$A016_04) = "Attitude Toward using Technology: Me gustaría trabajar con el robot."
comment(ds$A017_01) = "Self-Efficacy: Si no hubiera nadie cerca para decirme qué hacer mientras trabajo"
comment(ds$A017_02) = "Self-Efficacy: Si pudiera llamar a alguien para pedir ayuda si me quedo atascado."
comment(ds$A017_03) = "Self-Efficacy: Si tengo mucho tiempo para completar el trabajo para el cual se proporcionó el robot."
comment(ds$A017_04) = "Self-Efficacy: Si solo tuviera la función de ayuda incorporada para recibir asistencia."
comment(ds$A018_01) = "Behavioral Intention: Tengo la intención de usar el robot en los próximos 12 meses."
comment(ds$A018_02) = "Behavioral Intention: Preveo que usaré el robot en los próximos 24 meses."
comment(ds$A018_03) = "Behavioral Intention: Planeo usar el robot en los próximos 24 meses."
comment(ds$A019_01) = "Moderating Effect Ethics: Poco ético/Ético"
comment(ds$A019_02) = "Moderating Effect Ethics: Injusto/Justo"
comment(ds$A019_03) = "Moderating Effect Ethics: No es moralmente correcto/Moralmente correcto"
comment(ds$A019_04) = "Moderating Effect Ethics: No aceptable para mi familia/Aceptable para mi familia"
comment(ds$A019_05) = "Moderating Effect Ethics: Culturalmente inaceptable/Culturalmente aceptable"
comment(ds$A019_06) = "Moderating Effect Ethics: No es personalmente satisfactorio/Personalmente satisfactorio"
comment(ds$A019_07) = "Moderating Effect Ethics: Viola un contrato tácito/No viola un contrato tácito"
comment(ds$A110_01) = "General Rating: En general, calificaría al robot de manera positiva."
comment(ds$A110_02) = "General Rating: En general, apoyaría la integración de este robot en entornos de atención médica"
comment(ds$A111) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$A111_01) = "Use of Robots in Medical Settings: Hospitales generales"
comment(ds$A111_02) = "Use of Robots in Medical Settings: Hospitales pediátricos"
comment(ds$A111_03) = "Use of Robots in Medical Settings: Hospitales geriátricos"
comment(ds$A111_04) = "Use of Robots in Medical Settings: Hospitales psiquiátricos"
comment(ds$A111_05) = "Use of Robots in Medical Settings: Hospitales de traumatología y ortopedia"
comment(ds$A111_06) = "Use of Robots in Medical Settings: Otro campo, ¿cuál?"
comment(ds$A111_06a) = "Use of Robots in Medical Settings: Otro campo, ¿cuál? (free text)"
comment(ds$A112_01) = "Open Questions: ¿Cuáles son sus principales razones para aceptar o rechazar el uso de este robot en tareas de cuidado? Puede referirse a situaciones específicas, sentimientos o expectativas que tenga"
comment(ds$A112_02) = "Open Questions: ¿Ve algún riesgo o preocupación ética en el uso de este robot en el ámbito de la salud? Por favor, explíque su respuesta"
comment(ds$A112_03) = "Open Questions: Según su experiencia profesional, ¿qué cuestiones éticas cree que deberían considerarse al desarrollar o implementar este robot?"
comment(ds$A113_01) = "Performance Expectancy (PE): Consideraría útil al robot en mi trabajo."
comment(ds$A113_02) = "Performance Expectancy (PE): Usar el robot me permitiría realizar las tareas más rápidamente."
comment(ds$A113_03) = "Performance Expectancy (PE): Usar el robot aumentaría mi productividad."
comment(ds$A113_04) = "Performance Expectancy (PE): Si usara el robot, tendría más posibilidades de recibir un aumento."
comment(ds$A114_01) = "Attitude Toward using Technology: Mi interacción con el robot sería clara y comprensible."
comment(ds$A114_02) = "Attitude Toward using Technology: El robot haría que el trabajo fuera más interesante."
comment(ds$A114_03) = "Attitude Toward using Technology: Trabajar con el robot sería divertido."
comment(ds$A114_04) = "Attitude Toward using Technology: Me gustaría trabajar con el robot."
comment(ds$A115_01) = "Self-Efficacy: Si no hubiera nadie cerca para decirme qué hacer mientras trabajo"
comment(ds$A115_02) = "Self-Efficacy: Si pudiera llamar a alguien para pedir ayuda si me quedo atascado."
comment(ds$A115_03) = "Self-Efficacy: Si tengo mucho tiempo para completar el trabajo para el cual se proporcionó el robot."
comment(ds$A115_04) = "Self-Efficacy: Si solo tuviera la función de ayuda incorporada para recibir asistencia."
comment(ds$A116_01) = "Behavioral Intention: Tengo la intención de usar el robot en los próximos 12 meses."
comment(ds$A116_02) = "Behavioral Intention: Preveo que usaré el robot en los próximos 24 meses."
comment(ds$A116_03) = "Behavioral Intention: Planeo usar el robot en los próximos 24 meses."
comment(ds$A117_01) = "Moderating Effect Ethics: Poco ético/Ético"
comment(ds$A117_02) = "Moderating Effect Ethics: Injusto/Justo"
comment(ds$A117_03) = "Moderating Effect Ethics: No es moralmente correcto/Moralmente correcto"
comment(ds$A117_04) = "Moderating Effect Ethics: No aceptable para mi familia/Aceptable para mi familia"
comment(ds$A117_05) = "Moderating Effect Ethics: Culturalmente inaceptable/Culturalmente aceptable"
comment(ds$A117_06) = "Moderating Effect Ethics: No es personalmente satisfactorio/Personalmente satisfactorio"
comment(ds$A117_07) = "Moderating Effect Ethics: Viola un contrato tácito/No viola un contrato tácito"
comment(ds$A209_01) = "General Rating: En general, calificaría al robot de manera positiva."
comment(ds$A209_02) = "General Rating: En general, apoyaría la integración de este robot en entornos de atención médica."
comment(ds$A211) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$A211_01) = "Use of Robots in Medical Settings: Hospitales generales"
comment(ds$A211_02) = "Use of Robots in Medical Settings: Hospitales pediátricos"
comment(ds$A211_03) = "Use of Robots in Medical Settings: Hospitales geriátricos"
comment(ds$A211_04) = "Use of Robots in Medical Settings: Hospitales psiquiátricos"
comment(ds$A211_05) = "Use of Robots in Medical Settings: Hospitales de traumatología y ortopedia"
comment(ds$A211_06) = "Use of Robots in Medical Settings: Otro campo, ¿cuál?"
comment(ds$A211_06a) = "Use of Robots in Medical Settings: Otro campo, ¿cuál? (free text)"
comment(ds$A212_01) = "Open Questions: ¿Cuáles son sus principales razones para aceptar o rechazar el uso de este robot en tareas de cuidado? Puede referirse a situaciones específicas, sentimientos o expectativas que tenga"
comment(ds$A212_02) = "Open Questions: ¿Ve algún riesgo o preocupación ética en el uso de este robot en el ámbito de la salud? Por favor, explíque su respuesta"
comment(ds$A212_03) = "Open Questions: Según su experiencia profesional, ¿qué cuestiones éticas cree que deberían considerarse al desarrollar o implementar este robot?"
comment(ds$A213_01) = "Performance Expectancy (PE): Consideraría útil al robot en mi trabajo."
comment(ds$A213_02) = "Performance Expectancy (PE): Usar el robot me permitiría realizar las tareas más rápidamente."
comment(ds$A213_03) = "Performance Expectancy (PE): Usar el robot aumentaría mi productividad."
comment(ds$A213_04) = "Performance Expectancy (PE): Si usara el robot, tendría más posibilidades de recibir un aumento."
comment(ds$A214_01) = "Attitude Toward using Technology: Mi interacción con el robot sería clara y comprensible."
comment(ds$A214_02) = "Attitude Toward using Technology: El robot haría que el trabajo fuera más interesante."
comment(ds$A214_03) = "Attitude Toward using Technology: Trabajar con el robot sería divertido."
comment(ds$A214_04) = "Attitude Toward using Technology: Me gustaría trabajar con el robot."
comment(ds$A215_01) = "Self-Efficacy: Si no hubiera nadie cerca para decirme qué hacer mientras trabajo"
comment(ds$A215_02) = "Self-Efficacy: Si pudiera llamar a alguien para pedir ayuda si me quedo atascado."
comment(ds$A215_03) = "Self-Efficacy: Si tengo mucho tiempo para completar el trabajo para el cual se proporcionó el robot."
comment(ds$A215_04) = "Self-Efficacy: Si solo tuviera la función de ayuda incorporada para recibir asistencia."
comment(ds$A216_01) = "Behavioral Intention: Tengo la intención de usar el robot en los próximos 12 meses."
comment(ds$A216_02) = "Behavioral Intention: Preveo que usaré el robot en los próximos 24 meses."
comment(ds$A216_03) = "Behavioral Intention: Planeo usar el robot en los próximos 24 meses."
comment(ds$A217_01) = "Moderating Effect Ethics: Poco ético/Ético"
comment(ds$A217_02) = "Moderating Effect Ethics: Injusto/Justo"
comment(ds$A217_03) = "Moderating Effect Ethics: No es moralmente correcto/Moralmente correcto"
comment(ds$A217_04) = "Moderating Effect Ethics: No aceptable para mi familia/Aceptable para mi familia"
comment(ds$A217_05) = "Moderating Effect Ethics: Culturalmente inaceptable/Culturalmente aceptable"
comment(ds$A217_06) = "Moderating Effect Ethics: No es personalmente satisfactorio/Personalmente satisfactorio"
comment(ds$A217_07) = "Moderating Effect Ethics: Viola un contrato tácito/No viola un contrato tácito"
comment(ds$A310_01) = "General Rating: En general, calificaría al robot de manera positiva."
comment(ds$A310_02) = "General Rating: En general, apoyaría la integración de este robot en entornos de atención médica."
comment(ds$A311) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$A311_01) = "Use of Robots in Medical Settings: Hospitales generales"
comment(ds$A311_02) = "Use of Robots in Medical Settings: Hospitales pediátricos"
comment(ds$A311_03) = "Use of Robots in Medical Settings: Hospitales geriátricos"
comment(ds$A311_04) = "Use of Robots in Medical Settings: Hospitales psiquiátricos"
comment(ds$A311_05) = "Use of Robots in Medical Settings: Hospitales de traumatología y ortopedia"
comment(ds$A311_06) = "Use of Robots in Medical Settings: Otro campo, ¿cuál?"
comment(ds$A311_06a) = "Use of Robots in Medical Settings: Otro campo, ¿cuál? (free text)"
comment(ds$A312_01) = "Open Questions: ¿Cuáles son sus principales razones para aceptar o rechazar el uso de este robot en tareas de cuidado? Puede referirse a situaciones específicas, sentimientos o expectativas que tenga"
comment(ds$A312_02) = "Open Questions: ¿Ve algún riesgo o preocupación ética en el uso de este robot en el ámbito de la salud? Por favor, explíque su respuesta"
comment(ds$A312_03) = "Open Questions: Según su experiencia profesional, ¿qué cuestiones éticas cree que deberían considerarse al desarrollar o implementar este robot?"
comment(ds$A313_01) = "Performance Expectancy (PE): Consideraría útil al robot en mi trabajo."
comment(ds$A313_02) = "Performance Expectancy (PE): Usar el robot me permitiría realizar las tareas más rápidamente."
comment(ds$A313_03) = "Performance Expectancy (PE): Usar el robot aumentaría mi productividad."
comment(ds$A313_04) = "Performance Expectancy (PE): Si usara el robot, tendría más posibilidades de recibir un aumento."
comment(ds$A314_01) = "Attitude Toward using Technology: Mi interacción con el robot sería clara y comprensible."
comment(ds$A314_02) = "Attitude Toward using Technology: El robot haría que el trabajo fuera más interesante."
comment(ds$A314_03) = "Attitude Toward using Technology: Trabajar con el robot sería divertido."
comment(ds$A314_04) = "Attitude Toward using Technology: Me gustaría trabajar con el robot."
comment(ds$A315_01) = "Self-Efficacy: Si no hubiera nadie cerca para decirme qué hacer mientras trabajo."
comment(ds$A315_02) = "Self-Efficacy: Si pudiera llamar a alguien para pedir ayuda si me quedo atascado."
comment(ds$A315_03) = "Self-Efficacy: Si tengo mucho tiempo para completar el trabajo para el cual se proporcionó el robot."
comment(ds$A315_04) = "Self-Efficacy: Si solo tuviera la función de ayuda incorporada para recibir asistencia."
comment(ds$A316_01) = "Behavioral Intention: Tengo la intención de usar el robot en los próximos 12 meses."
comment(ds$A316_02) = "Behavioral Intention: Preveo que usaré el robot en los próximos 24 meses."
comment(ds$A316_03) = "Behavioral Intention: Planeo usar el robot en los próximos 24 meses."
comment(ds$A317_01) = "Moderating Effect Ethics: Poco ético/Ético"
comment(ds$A317_02) = "Moderating Effect Ethics: Injusto/Justo"
comment(ds$A317_03) = "Moderating Effect Ethics: No es moralmente correcto/Moralmente correcto"
comment(ds$A317_04) = "Moderating Effect Ethics: No aceptable para mi familia/Aceptable para mi familia"
comment(ds$A317_05) = "Moderating Effect Ethics: Culturalmente inaceptable/Culturalmente aceptable"
comment(ds$A317_06) = "Moderating Effect Ethics: No es personalmente satisfactorio/Personalmente satisfactorio"
comment(ds$A317_07) = "Moderating Effect Ethics: Viola un contrato tácito/No viola un contrato tácito"
comment(ds$A401) = "Informed Consent"
comment(ds$A701_01) = "Age: Edad"
comment(ds$A702) = "Gender"
comment(ds$A702_05) = "Gender: Prefiero describirme como"
comment(ds$A703) = "Years of experience in the field"
comment(ds$A705_01) = "Country: ¿Desde qué país está respondiendo este cuestionario?"
comment(ds$D101_01) = "General Rating: Overall, I would rate the robot positively."
comment(ds$D101_02) = "General Rating: Overall, I would support the integration of this robot in healthcare settings."
comment(ds$D102) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$D102_01) = "Use of Robots in Medical Settings: General Hospitals"
comment(ds$D102_02) = "Use of Robots in Medical Settings: Pediatric Hospitals"
comment(ds$D102_03) = "Use of Robots in Medical Settings: Geriatric Hospitals"
comment(ds$D102_04) = "Use of Robots in Medical Settings: Psiquiatric Hospitals"
comment(ds$D102_05) = "Use of Robots in Medical Settings: Trauma and Orthopedic Hospitals"
comment(ds$D102_06) = "Use of Robots in Medical Settings: Another field, which one?"
comment(ds$D102_06a) = "Use of Robots in Medical Settings: Another field, which one? (free text)"
comment(ds$D103_01) = "Open Questions: What are your main reasons for accepting or rejecting the use of this robot in caregiving tasks? You may refer to specific situations, feelings, or expectations you have."
comment(ds$D103_02) = "Open Questions: Do you see any risks or ethical concerns in using this robot in healthcare? Please explain your answer."
comment(ds$D103_03) = "Open Questions: Based on your professional experience, what ethical issues do you think should be considered when developing or implementing this robot?"
comment(ds$D104_01) = "Performance Expectancy (PE): I would find the robot useful in my job"
comment(ds$D104_02) = "Performance Expectancy (PE): Using the robot would enable me to accomplish tasks more quickly."
comment(ds$D104_03) = "Performance Expectancy (PE): Using the robot would increase my productivity."
comment(ds$D104_04) = "Performance Expectancy (PE): If I used the robot, I would have more chances of getting a raise."
comment(ds$D105_01) = "Attitude Toward using Technology: My interaction with the robot would be clear and understandable"
comment(ds$D105_02) = "Attitude Toward using Technology: The robot would make work more interesting."
comment(ds$D105_03) = "Attitude Toward using Technology: Working with the robot would be fun"
comment(ds$D105_04) = "Attitude Toward using Technology: I would like to work with the robot."
comment(ds$D106_01) = "Self-Efficacy: If there was no one around to tell me what to do as I go."
comment(ds$D106_02) = "Self-Efficacy: If I could call someone for help if I got stuck."
comment(ds$D106_03) = "Self-Efficacy: If I have a lot of time to complete the job for which the robot was provided."
comment(ds$D106_04) = "Self-Efficacy: If I would have just the built-in help facility for assistance."
comment(ds$D107_01) = "Behavioral Intention: I would intend to use the robot in the next 12 months"
comment(ds$D107_02) = "Behavioral Intention: I predict I would use the robot in the next 24 months"
comment(ds$D107_03) = "Behavioral Intention: I plan to use the robot in the next 24 months."
comment(ds$D108_01) = "Moderating Effect Ethics: Unethical/Ethical"
comment(ds$D108_02) = "Moderating Effect Ethics: Unfair/Fair"
comment(ds$D108_03) = "Moderating Effect Ethics: Not morally right/Morally right"
comment(ds$D108_04) = "Moderating Effect Ethics: Not acceptable to my family/Acceptable to my family"
comment(ds$D108_05) = "Moderating Effect Ethics: Culturally unacceptable/Culturally acceptable"
comment(ds$D108_06) = "Moderating Effect Ethics: Not personally satisfying/Personally satisfying"
comment(ds$D108_07) = "Moderating Effect Ethics: Violates an unwritten contract/Does not violate an unwritten contract"
comment(ds$D201_01) = "General Rating: Overall, I would rate the robot positively."
comment(ds$D201_02) = "General Rating: Overall, I would support the integration of this robot in healthcare settings."
comment(ds$D202) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$D202_01) = "Use of Robots in Medical Settings: General Hospitals"
comment(ds$D202_02) = "Use of Robots in Medical Settings: Pediatric Hospitals"
comment(ds$D202_03) = "Use of Robots in Medical Settings: Geriatric Hospitals"
comment(ds$D202_04) = "Use of Robots in Medical Settings: Psiquiatric Hospitals"
comment(ds$D202_05) = "Use of Robots in Medical Settings: Trauma and Orthopedic Hospitals"
comment(ds$D202_06) = "Use of Robots in Medical Settings: Another field, which one?"
comment(ds$D202_06a) = "Use of Robots in Medical Settings: Another field, which one? (free text)"
comment(ds$D203_01) = "Open Questions: What are your main reasons for accepting or rejecting the use of this robot in caregiving tasks? You may refer to specific situations, feelings, or expectations you have."
comment(ds$D203_02) = "Open Questions: Do you see any risks or ethical concerns in using this robot in healthcare? Please explain your answer."
comment(ds$D203_03) = "Open Questions: Based on your professional experience, what ethical issues do you think should be considered when developing or implementing this robot?"
comment(ds$D204_01) = "Performance Expectancy (PE): I would find the robot useful in my job"
comment(ds$D204_02) = "Performance Expectancy (PE): Using the robot would enable me to accomplish tasks more quickly."
comment(ds$D204_03) = "Performance Expectancy (PE): Using the robot would increase my productivity."
comment(ds$D204_04) = "Performance Expectancy (PE): If I used the robot, I would have more chances of getting a raise."
comment(ds$D205_01) = "Attitude Toward using Technology: My interaction with the robot would be clear and understandable"
comment(ds$D205_02) = "Attitude Toward using Technology: The robot would make work more interesting."
comment(ds$D205_03) = "Attitude Toward using Technology: Working with the robot would be fun"
comment(ds$D205_04) = "Attitude Toward using Technology: I would like to work with the robot."
comment(ds$D206_01) = "Self-Efficacy: If there was no one around to tell me what to do as I go."
comment(ds$D206_02) = "Self-Efficacy: If I could call someone for help if I got stuck."
comment(ds$D206_03) = "Self-Efficacy: If I have a lot of time to complete the job for which the robot was provided."
comment(ds$D206_04) = "Self-Efficacy: If I would have just the built-in help facility for assistance."
comment(ds$D207_01) = "Behavioral Intention: I would intend to use the robot in the next 12 months"
comment(ds$D207_02) = "Behavioral Intention: I predict I would use the robot in the next 24 months"
comment(ds$D207_03) = "Behavioral Intention: I plan to use the robot in the next 24 months."
comment(ds$D208_01) = "Moderating Effect Ethics: Unethical/Ethical"
comment(ds$D208_02) = "Moderating Effect Ethics: Unfair/Fair"
comment(ds$D208_03) = "Moderating Effect Ethics: Not acceptable to my family/Acceptable to my family"
comment(ds$D208_04) = "Moderating Effect Ethics: Culturally unacceptable/Culturally acceptable"
comment(ds$D208_05) = "Moderating Effect Ethics: Not personally satisfying/Personally satisfying"
comment(ds$D208_06) = "Moderating Effect Ethics: Violates an unwritten contract/Does not violate an unwritten contract"
comment(ds$D301_01) = "General Rating: Overall, I would rate the robot positively."
comment(ds$D301_02) = "General Rating: Overall, I would support the integration of this robot in healthcare settings."
comment(ds$D302) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$D302_01) = "Use of Robots in Medical Settings: General Hospitals"
comment(ds$D302_02) = "Use of Robots in Medical Settings: Pediatric Hospitals"
comment(ds$D302_03) = "Use of Robots in Medical Settings: Geriatric Hospitals"
comment(ds$D302_04) = "Use of Robots in Medical Settings: Psiquiatric Hospitals"
comment(ds$D302_05) = "Use of Robots in Medical Settings: Trauma and Orthopedic Hospitals"
comment(ds$D302_06) = "Use of Robots in Medical Settings: Another field, which one?"
comment(ds$D302_06a) = "Use of Robots in Medical Settings: Another field, which one? (free text)"
comment(ds$D303_01) = "Open Questions: What are your main reasons for accepting or rejecting the use of this robot in caregiving tasks? You may refer to specific situations, feelings, or expectations you have."
comment(ds$D303_02) = "Open Questions: Do you see any risks or ethical concerns in using this robot in healthcare? Please explain your answer."
comment(ds$D303_03) = "Open Questions: Based on your professional experience, what ethical issues do you think should be considered when developing or implementing this robot?"
comment(ds$D304_01) = "Performance Expectancy (PE): I would find the robot useful in my job"
comment(ds$D304_02) = "Performance Expectancy (PE): Using the robot would enable me to accomplish tasks more quickly."
comment(ds$D304_03) = "Performance Expectancy (PE): Using the robot would increase my productivity."
comment(ds$D304_04) = "Performance Expectancy (PE): If I used the robot, I would have more chances of getting a raise."
comment(ds$D305_01) = "Attitude Toward using Technology: My interaction with the robot would be clear and understandable"
comment(ds$D305_02) = "Attitude Toward using Technology: The robot would make work more interesting."
comment(ds$D305_03) = "Attitude Toward using Technology: Working with the robot would be fun"
comment(ds$D305_04) = "Attitude Toward using Technology: I would like to work with the robot."
comment(ds$D306_01) = "Self-Efficacy: If there was no one around to tell me what to do as I go."
comment(ds$D306_02) = "Self-Efficacy: If I could call someone for help if I got stuck."
comment(ds$D306_03) = "Self-Efficacy: If I have a lot of time to complete the job for which the robot was provided."
comment(ds$D306_04) = "Self-Efficacy: If I would have just the built-in help facility for assistance."
comment(ds$D307_01) = "Behavioral Intention: I would intend to use the robot in the next 12 months"
comment(ds$D307_02) = "Behavioral Intention: I predict I would use the robot in the next 24 months"
comment(ds$D307_03) = "Behavioral Intention: I plan to use the robot in the next 24 months."
comment(ds$D308_01) = "Moderating Effect Ethics: Unethical/Ethical"
comment(ds$D308_02) = "Moderating Effect Ethics: Unfair/Fair"
comment(ds$D308_03) = "Moderating Effect Ethics: Not acceptable to my family/Acceptable to my family"
comment(ds$D308_04) = "Moderating Effect Ethics: Culturally unacceptable/Culturally acceptable"
comment(ds$D308_05) = "Moderating Effect Ethics: Not personally satisfying/Personally satisfying"
comment(ds$D308_06) = "Moderating Effect Ethics: Violates an unwritten contract/Does not violate an unwritten contract"
comment(ds$D401_01) = "General Rating: Overall, I would rate the robot positively."
comment(ds$D401_02) = "General Rating: Overall, I would support the integration of this robot in healthcare settings."
comment(ds$D402) = "Use of Robots in Medical Settings: Residual option (negative) or number of selected options"
comment(ds$D402_01) = "Use of Robots in Medical Settings: General Hospitals"
comment(ds$D402_02) = "Use of Robots in Medical Settings: Pediatric Hospitals"
comment(ds$D402_03) = "Use of Robots in Medical Settings: Geriatric Hospitals"
comment(ds$D402_04) = "Use of Robots in Medical Settings: Psiquiatric Hospitals"
comment(ds$D402_05) = "Use of Robots in Medical Settings: Trauma and Orthopedic Hospitals"
comment(ds$D402_06) = "Use of Robots in Medical Settings: Another field, which one?"
comment(ds$D402_06a) = "Use of Robots in Medical Settings: Another field, which one? (free text)"
comment(ds$D403_01) = "Open Questions: What are your main reasons for accepting or rejecting the use of this robot in caregiving tasks? You may refer to specific situations, feelings, or expectations you have."
comment(ds$D403_02) = "Open Questions: Do you see any risks or ethical concerns in using this robot in healthcare? Please explain your answer."
comment(ds$D403_03) = "Open Questions: Based on your professional experience, what ethical issues do you think should be considered when developing or implementing this robot?"
comment(ds$D404_01) = "Performance Expectancy (PE): I would find the robot useful in my job"
comment(ds$D404_02) = "Performance Expectancy (PE): Using the robot would enable me to accomplish tasks more quickly."
comment(ds$D404_03) = "Performance Expectancy (PE): Using the robot would increase my productivity."
comment(ds$D404_04) = "Performance Expectancy (PE): If I used the robot, I would have more chances of getting a raise."
comment(ds$D405_01) = "Attitude Toward using Technology: My interaction with the robot would be clear and understandable"
comment(ds$D405_02) = "Attitude Toward using Technology: The robot would make work more interesting."
comment(ds$D405_03) = "Attitude Toward using Technology: Working with the robot would be fun"
comment(ds$D405_04) = "Attitude Toward using Technology: I would like to work with the robot."
comment(ds$D406_01) = "Self-Efficacy: If there was no one around to tell me what to do as I go."
comment(ds$D406_02) = "Self-Efficacy: If I could call someone for help if I got stuck."
comment(ds$D406_03) = "Self-Efficacy: If I have a lot of time to complete the job for which the robot was provided."
comment(ds$D406_04) = "Self-Efficacy: If I would have just the built-in help facility for assistance."
comment(ds$D407_01) = "Behavioral Intention: I would intend to use the robot in the next 12 months"
comment(ds$D407_02) = "Behavioral Intention: I predict I would use the robot in the next 24 months"
comment(ds$D407_03) = "Behavioral Intention: I plan to use the robot in the next 24 months."
comment(ds$D408_01) = "Moderating Effect Ethics: Unethical/Ethical"
comment(ds$D408_02) = "Moderating Effect Ethics: Unfair/Fair"
comment(ds$D408_03) = "Moderating Effect Ethics: Not acceptable to my family/Acceptable to my family"
comment(ds$D408_04) = "Moderating Effect Ethics: Culturally unacceptable/Culturally acceptable"
comment(ds$D408_05) = "Moderating Effect Ethics: Not personally satisfying/Personally satisfying"
comment(ds$D408_06) = "Moderating Effect Ethics: Violates an unwritten contract/Does not violate an unwritten contract"
comment(ds$D501) = "Informed Consent"
comment(ds$D801_01) = "Age: Age"
comment(ds$D802) = "Gender"
comment(ds$D803) = "Years of experience in the field"
comment(ds$D804_01) = "Country: From which country are you responding to this questionnaire?"
comment(ds$RA01_CP) = "Block rotation: Complete clearances of the ballot, yet"
comment(ds$RA01) = "Block rotation: Code drawn"
comment(ds$TIME001) = "Time spent on page 1"
comment(ds$TIME002) = "Time spent on page 2"
comment(ds$TIME003) = "Time spent on page 3"
comment(ds$TIME004) = "Time spent on page 4"
comment(ds$TIME005) = "Time spent on page 5"
comment(ds$TIME006) = "Time spent on page 6"
comment(ds$TIME007) = "Time spent on page 7"
comment(ds$TIME008) = "Time spent on page 8"
comment(ds$TIME009) = "Time spent on page 9"
comment(ds$TIME010) = "Time spent on page 10"
comment(ds$TIME011) = "Time spent on page 11"
comment(ds$TIME012) = "Time spent on page 12"
comment(ds$TIME013) = "Time spent on page 13"
comment(ds$TIME014) = "Time spent on page 14"
comment(ds$TIME015) = "Time spent on page 15"
comment(ds$TIME016) = "Time spent on page 16"
comment(ds$TIME017) = "Time spent on page 17"
comment(ds$TIME018) = "Time spent on page 18"
comment(ds$TIME019) = "Time spent on page 19"
comment(ds$TIME020) = "Time spent on page 20"
comment(ds$TIME021) = "Time spent on page 21"
comment(ds$TIME022) = "Time spent on page 22"
comment(ds$TIME023) = "Time spent on page 23"
comment(ds$TIME024) = "Time spent on page 24"
comment(ds$TIME025) = "Time spent on page 25"
comment(ds$TIME_SUM) = "Time spent overall (except outliers)"
comment(ds$MAILSENT) = "Time when the invitation mailing was sent (personally identifiable recipients, only)"
comment(ds$LASTDATA) = "Time when the data was most recently updated"
comment(ds$STATUS) = "Interview status marker"
comment(ds$FINISHED) = "Has the interview been finished (reached last page)?"
comment(ds$Q_VIEWER) = "Did the respondent only view the questionnaire, omitting mandatory questions?"
comment(ds$LASTPAGE) = "Last page that the participant has handled in the questionnaire"
comment(ds$MAXPAGE) = "Hindmost page handled by the participant"
comment(ds$MISSING) = "Missing answers in percent"
comment(ds$MISSREL) = "Missing answers (weighted by relevance)"
comment(ds$TIME_RSI) = "Completion Speed (relative)"


# Assure that the comments are retained in subsets
as.data.frame.avector = as.data.frame.vector
`[.avector` <- function(x,i,...) {
  r <- NextMethod("[")
  mostattributes(r) <- attributes(x)
  r
}
ds_tmp = data.frame(
  lapply(ds, function(x) {
    structure( x, class = c("avector", class(x) ) )
  } )
)
mostattributes(ds_tmp) = attributes(ds)
ds = ds_tmp
rm(ds_tmp)
```

## fix error

set levels to max 120 characters to avoid error when saving as .sav

```{r}
library(stringr)

# Apply truncation to the levels of all respective factors
levels(ds$A401) <- str_trunc(levels(ds$A401), width = 120)
levels(ds$D501) <- str_trunc(levels(ds$D501), width = 120)

# Check the results
levels(ds$A401)
levels(ds$D501)
```


# get all columns containing text answers

```{r}
extract_string_vars_with_3_words <- function(ds) {
  ds %>%
    select(where(is.character)) %>%
    select(where(~ any(str_count(., "\\S+") >= 3, na.rm = TRUE))) %>%
    names()
}
vars <- extract_string_vars_with_3_words(ds)
vars

for(v in vars){
  cat("\n\n#######\n", v, "entries:\n", as.vector(ds[complete.cases(ds[, v]), v])[[1]][1:3])
}
```


```{r}
cat(paste0("'", vars, "',"))
```



# save data sets


```{r}
setwd("outputs")

saveRDS(ds, file = paste0("ds", ".rds"))
writexl::write_xlsx(x = ds, path = paste0("ds", ".xlsx"))
write.csv2(x = ds, file =  paste0("ds", ".csv"))
haven::write_sav(data = ds, path = paste0("ds", ".sav"))
```

